name: CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dongurami-front"
          heroku_email: "junsang.yu3@gmail.com"
        env:
          HD_NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
